import { readFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * The shared layout for every Open Graph card on the site.
 *
 * One component per job (CLAUDE.md rule 5): the home page, the events index and every
 * individual event all render through this, so a shared link looks the same wherever it
 * is pasted and there is only one file to change.
 *
 * Constraints worth knowing before editing:
 * - Satori — the renderer behind ImageResponse — supports **flexbox only**. No grid, and
 *   any element with more than one child needs an explicit `display: "flex"`.
 * - Tailwind classes do nothing here. These are inline styles by necessity, which is the
 *   one sanctioned exception to the no-inline-styles rule; the token values are repeated
 *   as literals below because the CSS custom properties aren't available to the renderer.
 * - The whole bundle, images included, must stay under 500 KB.
 */

const PAPER = "#ECE9E2";
const INK = "#1F1F1F";
const INK_3 = "#6B6760";
const NAVY = "#13297A";
const YELLOW = "#FFC83D";

export const OG_SIZE = { width: 1200, height: 630 };
export const OG_CONTENT_TYPE = "image/png";

/**
 * A 240px copy of the official logo, pre-generated by `pnpm optimize-images`.
 *
 * The full-size logo.png is 154 KB, which base64-encodes to over 200 KB of the 500 KB
 * budget for a mark that renders at 128px. Read once at module scope: these cards are
 * generated at build time, so this happens once per build, not once per card.
 */
const logoPromise = readFile(join(process.cwd(), "public/images/brand/logo-og.png")).then(
  (buffer) => `data:image/png;base64,${buffer.toString("base64")}`,
);

export type OgCardProps = {
  /** The small navy label above the title — a category, or the site name. */
  eyebrow: string;
  title: string;
  /** Optional supporting line: a date, a venue, a one-line summary. */
  meta?: string;
};

export async function OgCard({ eyebrow, title, meta }: OgCardProps) {
  const logo = await logoPromise;

  // Long event titles need to stay on a card that's only 630px tall. Three sizes rather
  // than a continuous scale: enough to keep every real title inside the frame.
  const titleSize = title.length > 58 ? 64 : title.length > 34 ? 82 : 104;

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        backgroundColor: PAPER,
        color: INK,
        fontFamily: "sans-serif",
      }}
    >
      {/* The hazard stripe from the posters, rebuilt as a gradient — Satori has no
          repeating-linear-gradient, so this is a plain one at the same angle. */}
      <div
        style={{
          display: "flex",
          height: 14,
          width: "100%",
          background: `linear-gradient(90deg, ${YELLOW} 0%, ${YELLOW} 55%, ${NAVY} 55%, ${NAVY} 100%)`,
        }}
      />

      <div
        style={{
          display: "flex",
          flex: 1,
          alignItems: "center",
          justifyContent: "space-between",
          padding: "56px 72px",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            maxWidth: 740,
          }}
        >
          <div
            style={{
              display: "flex",
              fontSize: 26,
              letterSpacing: 4,
              textTransform: "uppercase",
              color: NAVY,
              fontWeight: 700,
            }}
          >
            {eyebrow}
          </div>

          <div
            style={{
              display: "flex",
              marginTop: 24,
              fontSize: titleSize,
              lineHeight: 1.04,
              fontWeight: 800,
              letterSpacing: -2,
            }}
          >
            {title}
          </div>

          {meta ? (
            <div
              style={{
                display: "flex",
                marginTop: 28,
                fontSize: 28,
                color: INK_3,
              }}
            >
              {meta}
            </div>
          ) : null}
        </div>

        {/* The logo is used exactly as shipped: square, dark background, never recoloured
            or cropped (CLAUDE.md, "The logo is fixed").

            A raw <img> is required here — this tree is rendered by Satori into a PNG, not
            by a browser, so next/image has nothing to optimise and its output (srcset,
            lazy loading) would not render at all. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={logo} width={168} height={168} alt="" style={{ borderRadius: 12 }} />
      </div>

      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "0 72px 44px",
          fontSize: 24,
          color: INK_3,
        }}
      >
        <div style={{ display: "flex" }}>E-Cell, JNTU Hyderabad</div>
        <div style={{ display: "flex", letterSpacing: 2 }}>INNOVATE · CONNECT · ELEVATE</div>
      </div>
    </div>
  );
}
